[tool.ruff]
line-length = 88
target-version = "py312"
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "migrations",
    ".pytest_cache",
    "htmlcov",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "DJ", "UP"]
ignore = ["E203"] # Whitespace before ':' (conflicts with some formatters)

[tool.ruff.lint.per-file-ignores]
# Ignore linting errors in migrations
"**/migrations/*" = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
